spring:
  application:
    name: my-spring-boot-project

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:my_spring_boot_db}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        "[format_sql]": ${JPA_FORMAT_SQL:true}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    "[com.vtlong.my_spring_boot_project]": ${LOG_LEVEL:INFO}
    "[org.hibernate.SQL]": ${LOG_SQL:DEBUG}
    "[org.hibernate.type.descriptor.sql.BasicBinder]": ${LOG_SQL_PARAMS:TRACE}
    "[org.springframework.web]": ${LOG_WEB:INFO}
    "[org.springframework.security]": ${LOG_SECURITY:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 30
